### ISSUE TITLE
TypeError: htmlImages is not a function

### ISSUE THREAD

**Issue by lknlknim** [Jax-p/vite-plugin-html-images#1]
Is there working demo project/template?
I tried in both Svelte and SvelteKit projects, both complain about htmlImages is not a function and stopped.

`failed to load config from C:\Projects\vite-project\vite.config.js
error when starting dev server:
TypeError: htmlImages is not a function
    at file:///C:/Projects/vite-project/vite.config.js?t=1642586823351:7:23
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (C:\Projects\vite-project\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\chunks\dep-f5552faa.js:75089:31)
    at async resolveConfig (C:\Projects\vite-project\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\chunks\dep-f5552faa.js:74656:28)
    at async createServer (C:\Projects\vite-project\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\chunks\dep-f5552faa.js:60326:20)
    at async CAC.<anonymous> (C:\Projects\vite-project\node_modules\.pnpm\vite@2.7.13\node_modules\vite\dist\node\cli.js:688:24)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by liamdiprose** [comment]
```patch
diff --git a/package.json b/package.json
index 37baf39..81917fc 100644
--- a/package.json
+++ b/package.json
@@ -2,7 +2,8 @@
   "name": "vite-plugin-html-images",
   "version": "0.1.2",
   "description": "Transforms images with query parameters from HTML",
-  "main": "dist/index.js",
+  "main": "dist/index.mjs",
+  "type": "module",
   "author": "Jax-p",
   "license": "MIT",
   "private": false,
```

**Comment by yisenliu** [comment]
It's not working even modifing package.json, nothing happened in the output html.

**Comment by wpmiro** [comment]
It's work for my.
